### ISSUE TITLE
BitCoin Transaction Visualization Issues

### ISSUE THREAD

**Issue by e3024650** [puzzledsean/BitPlanet#8]
@FreddieV4 Hi I have a requirement of implementing bitcoin transaction for few nodes. Can i make use of this code. if yes i have few doubts like
1. I dont see index html here, where i can see the visualization. Plz help

**Comment by freddiev4** [comment]
@e3024650 There is no "index.html", as it's a Node.js application that uses EJS templating. This project is also still a work-in-progress.

**Comment by e3024650** [comment]
@FreddieV4 Thank for your reply

**Comment by e3024650** [comment]
@FreddieV4 Thanks for your reply
